package org.gtlcore.gtlcore.client.renderer.machine;

import net.minecraft.client.renderer.LightTexture;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.block.model.BakedQuad;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.client.resources.model.BakedModel;
import net.minecraft.core.Direction;
import net.minecraft.util.Mth;
import net.minecraft.util.RandomSource;
import net.minecraftforge.client.model.data.ModelData;
import net.minecraftforge.fml.ModList;

import com.mojang.blaze3d.vertex.BufferBuilder;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import org.lwjgl.system.MemoryStack;
import org.lwjgl.system.MemoryUtil;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.List;

/**
 * Batches immutable model data through Embeddium's existing vertex writer. Oculus still generates
 * its extended attributes and owns the render type, sorting, upload, shader and shadow passes.
 * Material IDs are regenerated by Oculus for every draw; no shader program is replaced.
 */
final class HarmonyShaderMesh implements AutoCloseable {

    // Opt in only when the installed Oculus encoder exposes the expected extended format.
    private static final int STRIDE = 56;
    private static final int MAX_VERTICES = 1 << 18;
    private static final BulkWriter WRITER = BulkWriter.find();
    private final float[] geometry;
    private final int[] attributes;
    private final float[] midUV;
    private final int vertexCount;
    private ByteBuffer output;

    private HarmonyShaderMesh(List<BakedQuad> quads, int count) {
        vertexCount = count;
        geometry = new float[count * 6];
        attributes = new int[count * 4];
        midUV = new float[count / 2];
        output = MemoryUtil.memCalloc(count * STRIDE);
        int index = 0, attribute = 0, mid = 0;
        for (var quad : quads) {
            int[] data = quad.getVertices();
            var direction = quad.getDirection();
            midUV[mid++] = (Float.intBitsToFloat(data[4]) + Float.intBitsToFloat(data[12]) +
                    Float.intBitsToFloat(data[20]) + Float.intBitsToFloat(data[28])) * .25f;
            midUV[mid++] = (Float.intBitsToFloat(data[5]) + Float.intBitsToFloat(data[13]) +
                    Float.intBitsToFloat(data[21]) + Float.intBitsToFloat(data[29])) * .25f;
            for (int vertex = 0; vertex < 4; vertex++) {
                int offset = vertex * 8;
                geometry[index++] = Float.intBitsToFloat(data[offset]);
                geometry[index++] = Float.intBitsToFloat(data[offset + 1]);
                geometry[index++] = Float.intBitsToFloat(data[offset + 2]);
                int normal = data[offset + 7];
                if ((normal & 0xffffff) == 0) {
                    geometry[index++] = direction.getStepX();
                    geometry[index++] = direction.getStepY();
                    geometry[index++] = direction.getStepZ();
                } else {
                    geometry[index++] = (byte) normal * (1.0f / 127.0f);
                    geometry[index++] = (byte) (normal >>> 8) * (1.0f / 127.0f);
                    geometry[index++] = (byte) (normal >>> 16) * (1.0f / 127.0f);
                }
                attributes[attribute++] = data[offset + 3];
                attributes[attribute++] = data[offset + 4];
                attributes[attribute++] = data[offset + 5];
                int light = data[offset + 6];
                attributes[attribute++] = Math.max(light & 255, LightTexture.FULL_BRIGHT & 255) |
                        Math.max(light >>> 16 & 255, LightTexture.FULL_BRIGHT >>> 16 & 255) << 16;
            }
        }
    }

    static boolean available() {
        return WRITER != null;
    }

    static boolean accepts(VertexConsumer consumer) {
        // Wrapped/decal consumers can rewrite UVs or colors. Leave them to the original path;
        // only the actual buffer builders are known to copy, rather than mutate, our source.
        if (WRITER == null || (consumer.getClass() != BufferBuilder.class &&
                !consumer.getClass().getName().equals("me.jellysquid.mods.sodium.client.render.vertex.buffer.SodiumBufferBuilder")))
            return false;
        try {
            return (boolean) WRITER.extended.invokeExact() && (boolean) WRITER.accepts.invokeExact(consumer);
        } catch (Throwable exception) {
            if (exception instanceof Error error) throw error;
            return false;
        }
    }

    static HarmonyShaderMesh create(BakedModel model, RenderType type) {
        var quads = new ArrayList<BakedQuad>();
        var random = RandomSource.create(42);
        for (Direction direction : Direction.values()) {
            random.setSeed(42);
            quads.addAll(model.getQuads(null, direction, random, ModelData.EMPTY, type));
        }
        random.setSeed(42);
        quads.addAll(model.getQuads(null, null, random, ModelData.EMPTY, type));
        if (quads.isEmpty() || quads.size() > MAX_VERTICES / 4) return null;
        for (var quad : quads) {
            int[] data = quad.getVertices();
            if (data.length != 32) return null;
            for (int vertex = 0; vertex < 4; vertex++) {
                for (int axis = 0; axis < 3; axis++) {
                    if (!Float.isFinite(Float.intBitsToFloat(data[vertex * 8 + axis]))) return null;
                }
            }
        }
        // Keep all four vertices, even the padded vertex of an OBJ triangle. The original
        // quad boundaries determine Iris tangents, mid-UVs and translucent sorting.
        return new HarmonyShaderMesh(quads, quads.size() * 4);
    }

    void write(PoseStack.Pose pose, VertexConsumer consumer) {
        var matrix = pose.pose();
        var normals = pose.normal();
        try (var stack = MemoryStack.stackPush()) {
            long target = MemoryUtil.memAddress(output);
            for (int vertex = 0, offset = 0; vertex < vertexCount; vertex++, offset += 6, target += STRIDE) {
                float x = geometry[offset], y = geometry[offset + 1], z = geometry[offset + 2];
                // Match the operation order of Oculus' model encoder, including the unquantized
                // last vertex normal used to generate each quad's tangent.
                float px = matrix.m00() * x + (matrix.m10() * y + (matrix.m20() * z + matrix.m30()));
                float py = matrix.m01() * x + (matrix.m11() * y + (matrix.m21() * z + matrix.m31()));
                float pz = matrix.m02() * x + (matrix.m12() * y + (matrix.m22() * z + matrix.m32()));
                x = geometry[offset + 3];
                y = geometry[offset + 4];
                z = geometry[offset + 5];
                float nx = normals.m00() * x + (normals.m10() * y + normals.m20() * z);
                float ny = normals.m01() * x + (normals.m11() * y + normals.m21() * z);
                float nz = normals.m02() * x + (normals.m12() * y + normals.m22() * z);
                int attribute = vertex * 4, mid = (vertex / 4) * 2;
                WRITER.vertex.invokeExact(target, px, py, pz, attributes[attribute],
                        Float.intBitsToFloat(attributes[attribute + 1]), Float.intBitsToFloat(attributes[attribute + 2]),
                        midUV[mid], midUV[mid + 1], attributes[attribute + 3], OverlayTexture.NO_OVERLAY,
                        normal(nx) | normal(ny) << 8 | normal(nz) << 16);
                if ((vertex & 3) == 3) {
                    WRITER.setupQuad.invokeExact(target, STRIDE);
                    int tangent = (int) WRITER.tangent.invokeExact(nx, ny, nz);
                    for (int corner = 0; corner < 4; corner++) {
                        MemoryUtil.memPutInt(target - (long) corner * STRIDE + WRITER.tangentOffset, tangent);
                    }
                }
            }
            WRITER.push.invokeExact(consumer, stack, MemoryUtil.memAddress(output), vertexCount);
        } catch (Throwable exception) {
            if (exception instanceof Error error) throw error;
            // Do not retry a partially written batch through the original renderer.
            throw new IllegalStateException("Could not submit harmony shader vertices", exception);
        }
    }

    private static int normal(float value) {
        return (int) (Mth.clamp(value, -1, 1) * 127) & 255;
    }

    @Override
    public void close() {
        if (output != null) {
            MemoryUtil.memFree(output);
            output = null;
        }
    }

    private record BulkWriter(MethodHandle accepts, MethodHandle extended, MethodHandle push, MethodHandle vertex,
                              MethodHandle setupQuad, MethodHandle tangent, int tangentOffset) {

        private static BulkWriter find() {
            if (!ModList.get().isLoaded("embeddium") || !ModList.get().isLoaded("oculus")) return null;
            try {
                Class<?> writer = Class.forName("net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter");
                Class<?> format = Class.forName("net.caffeinemc.mods.sodium.api.vertex.format.VertexFormatDescription");
                Class<?> encoder = Class.forName("net.irisshaders.iris.compat.sodium.impl.vertex_format.entity_xhfp.EntityVertex");
                Object modelFormat = encoder.getField("FORMAT").get(null);
                if ((int) format.getMethod("stride").invoke(modelFormat) != STRIDE) return null;
                if (encoder.getField("STRIDE").getInt(null) != STRIDE) return null;
                var lookup = MethodHandles.publicLookup();
                var extended = lookup.findStaticGetter(Class.forName("net.irisshaders.iris.vertices.ImmediateState"),
                        "renderWithExtendedVertexFormat", boolean.class);
                var vertex = lookup.findStatic(encoder, "write2", MethodType.methodType(void.class, long.class,
                        float.class, float.class, float.class, int.class, float.class, float.class, float.class, float.class,
                        int.class, int.class, int.class));
                Class<?> view = Class.forName("net.irisshaders.iris.compat.sodium.impl.vertex_format.entity_xhfp.QuadViewEntity$QuadViewEntityUnsafe");
                Object quadView = view.getConstructor().newInstance();
                var setupQuad = lookup.findVirtual(view, "setup", MethodType.methodType(void.class, long.class, int.class)).bindTo(quadView);
                var tangent = lookup.findStatic(Class.forName("net.irisshaders.iris.vertices.NormalHelper"), "computeTangent",
                        MethodType.methodType(int.class, float.class, float.class, float.class,
                                Class.forName("net.irisshaders.iris.vertices.views.TriView")));
                tangent = MethodHandles.insertArguments(tangent, 3, quadView);
                Class<?> attribute = Class.forName("net.caffeinemc.mods.sodium.api.vertex.attributes.CommonVertexAttribute");
                Object tangentAttribute = Class.forName("net.irisshaders.iris.compat.sodium.impl.vertex_format.IrisCommonVertexAttributes")
                        .getField("TANGENT").get(null);
                int tangentOffset = (int) format.getMethod("getElementOffset", attribute).invoke(modelFormat, tangentAttribute);
                if (tangentOffset < 0 || tangentOffset + Integer.BYTES > STRIDE) return null;
                var accepts = lookup.findVirtual(writer, "canUseIntrinsics", MethodType.methodType(boolean.class))
                        .asType(MethodType.methodType(boolean.class, VertexConsumer.class));
                var push = lookup.findVirtual(writer, "push", MethodType.methodType(void.class, MemoryStack.class, long.class, int.class, format));
                push = MethodHandles.insertArguments(push, 4, modelFormat)
                        .asType(MethodType.methodType(void.class, VertexConsumer.class, MemoryStack.class, long.class, int.class));
                return new BulkWriter(accepts, extended, push, vertex, setupQuad, tangent, tangentOffset);
            } catch (ReflectiveOperationException | LinkageError exception) {
                return null;
            }
        }
    }
}
