package org.gtlcore.gtlcore.integration.ae2.graph.core;

import java.math.BigInteger;
import java.util.*;

/** Ready queue for acyclic material flow, allowing tools conserved by every selected recipe. */
final class DagScheduler<K> {

    private final List<String> recipes;
    private final BigInteger[] remaining;
    private final boolean[] queued;
    private final long[] generation;
    private final Deque<Integer> ready = new ArrayDeque<>();
    private final PriorityQueue<Retry> retries = new PriorityQueue<>(Comparator.comparingLong(Retry::tick));
    private final Map<K, List<Integer>> consumers = new HashMap<>();
    private int unfinished;
    private int active = -1;

    private DagScheduler(Map<String, BigInteger> counts, Map<String, GraphRecipe<K>> recipes, Map<String, BigInteger> accepted) {
        this.recipes = List.copyOf(counts.keySet());
        remaining = new BigInteger[counts.size()];
        queued = new boolean[counts.size()];
        generation = new long[counts.size()];
        for (int i = 0; i < this.recipes.size(); i++) {
            String recipe = this.recipes.get(i);
            remaining[i] = counts.get(recipe).subtract(accepted.getOrDefault(recipe, BigInteger.ZERO));
            if (remaining[i].signum() < 0) throw new IllegalArgumentException("DAG accepted count exceeds plan");
            if (remaining[i].signum() > 0) {
                unfinished++;
                enqueue(i);
            }
            for (K key : recipes.get(recipe).inputs().keySet()) consumers.computeIfAbsent(key, ignored -> new ArrayList<>()).add(i);
        }
    }

    static <K> DagScheduler<K> create(GraphPlan<K> plan, Map<String, BigInteger> accepted) {
        // Count the shared program without expanding repeats. A long-sized order
        // can require more than long executions of an intermediate recipe.
        Map<String, BigInteger> counts = plan.patternTimesExact();
        List<String> steps = new ArrayList<>(counts.keySet());
        Set<K> conserved = conserved(steps.stream().map(plan.recipes()::get).toList());
        if (!conserved.containsAll(plan.seeds().keySet())) return null;
        Map<K, Integer> lastProducer = new HashMap<>();
        for (int i = 0; i < steps.size(); i++) {
            for (K output : plan.recipes().get(steps.get(i)).executionOutputs().keySet()) lastProducer.put(output, i);
        }
        for (int i = 0; i < steps.size(); i++) {
            for (K input : plan.recipes().get(steps.get(i)).inputs().keySet()) {
                // Every use returns exactly what it took. Actual owned stock
                // still gates dispatch, and all returns must arrive to finish.
                // Removing only these edges lets consumers free a full buffer
                // without imposing a serial barrier across a shared tool.
                if (conserved.contains(input)) continue;
                // No resource can be regenerated by this or any later operation.
                // Thus arbitrary ready-node dispatch cannot steal a cyclic seed.
                if (lastProducer.getOrDefault(input, -1) >= i) return null;
            }
        }
        return new DagScheduler<>(counts, plan.recipes(), accepted);
    }

    static <K> Set<K> conserved(Collection<GraphRecipe<K>> recipes) {
        Set<K> conserved = new HashSet<>(), changed = new HashSet<>();
        for (GraphRecipe<K> recipe : recipes) {
            recipe.inputs().forEach((key, input) -> {
                if (!recipe.configurationInputs().containsKey(key) && recipe.executionOutputs().getOrDefault(key, 0L).equals(input)) conserved.add(key);
                else changed.add(key);
            });
            recipe.executionOutputs().forEach((key, output) -> {
                if (!recipe.inputs().getOrDefault(key, 0L).equals(output)) changed.add(key);
            });
        }
        conserved.removeAll(changed);
        return conserved;
    }

    PlanStep.Batch poll(long tick) {
        while (!retries.isEmpty() && retries.peek().tick <= tick) {
            Retry retry = retries.remove();
            if (generation[retry.index] == retry.generation) enqueue(retry.index);
        }
        if (ready.isEmpty()) {
            active = -1;
            return null;
        }
        active = ready.removeFirst();
        queued[active] = false;
        return new PlanStep.Batch(recipes.get(active), ExactAmounts.capped(remaining[active]));
    }

    void accepted(long runs) {
        if (active < 0 || runs <= 0 || BigInteger.valueOf(runs).compareTo(remaining[active]) > 0) throw new IllegalArgumentException("No prepared DAG batch");
        remaining[active] = remaining[active].subtract(BigInteger.valueOf(runs));
        if (remaining[active].signum() == 0) unfinished--;
        else enqueue(active);
    }

    void retry(long tick) {
        if (active >= 0) retries.add(new Retry(active, tick, ++generation[active]));
    }

    void resourceChanged(K key) {
        for (int index : consumers.getOrDefault(key, List.of())) enqueue(index);
    }

    private void enqueue(int index) {
        if (remaining[index].signum() <= 0 || queued[index]) return;
        generation[index]++;
        queued[index] = true;
        ready.addLast(index);
    }

    boolean finished() {
        return unfinished == 0;
    }

    private record Retry(int index, long tick, long generation) {}
}
